### ISSUE TITLE
Has some issues with RGBA hex values

### ISSUE THREAD

**Issue by oliv3r** [chrisbra/Colorizer#104]
I was super excited to give this a go; but while 1 color sort-of, showed up; I got the following error:

```
Colorizer: Some error occurred here:  Colorize: ['#\%(\x\{3}\|\x\{6}\|\x\{8\}\)\%(\>\|[-_]\)\@=', function('<SNR>145_PreviewColorHex'), 'colorizer_hex', 1, []]
Colorizer: Position: [0, 57, 21, 0]
```
on the following yaml

```yaml
kibot:
  version: 1

global:
  environment:
    models_3d: '${KIPRJMOD}/packages3D'
  restore_project: true

preflight:
  run_drc: false
  run_erc: false
  set_text_variables:
    - name: 'VCS_PCB_DATE'
      command: 'date -d @$(git log -1 --format="%at" "${KIBOT_PCB_NAME}") -Idate'
    - name: 'VCS_PCB_TIMEDATE'
      command: 'date -d @$(git log -1 --format="%at" "${KIBOT_PCB_NAME}") -Iseconds'
    - name: 'VCS_PCB_HASH'
      command: 'git log -1 --format="%H" "${KIBOT_PCB_NAME}"'
      before: 'Git <'
      after: '>'
    - name: 'VCS_SCH_TIMEDATE'
      command: 'date -d @$(git log -1 --format="%at" "${KIBOT_SCH_NAME}") -Iseconds'
    - name: 'VCS_SCH_HASH'
      command: 'git log -1 --format="%H" "${KIBOT_SCH_NAME}"'
      before: 'Git <'
      after: '>'
    - name: 'VCS_TAG'
      command: 'git describe --always --dirty'
    - name: 'SHEETPATH' # Hack to avoid W082 Unknown sheetpath
      text: ''

outputs:
  - name: 'pdf_sch_print'
    comment: 'Exports the schematic to the most common exchange format. Suitable for printing.'
    type: 'pdf_sch_print'
    dir: 'outputs/pdf'
    options:
      all_pages: true
      background_color: false
      frame: true
      monochrome: false
  - name: 'pdf_pcb_print'
    comment: 'Exports the PCB to the most common exchange format. Suitable for printing.'
    type: 'pcb_print'
    dir: 'outputs/pdf'
    options:
      force_edge_cuts: true
      format: 'PDF'
      individual_page_scaling: false
      keep_temporal_files: false
      scaling: @KICAD_PDF_SCALING@
      pages:
        - sheet: 'PCB top'
          layers:
          - layer: 'F.Cu'
          - layer: 'F.Mask'
            color: '#14332440'
          - layer: 'F.SilkS'
            color: '#f2eda1ff'
        - sheet: 'Fabrication top'
          layers:
          - layer: 'F.Fab'
          - layer: 'F.Paste'
          - layer: 'F.Adhes'
          - layer: 'User.Comments'
        - sheet: 'Silkscreen top'
          layers:
          - layer: 'F.SilkS'
            color: '#00000000'
        - sheet: 'F.Cu'
          layers:
          - layer: 'F.Cu'
        - sheet: '%ln layer'
          repeat_for_layer: 'F.Cu'
          repeat_layers: 'inners'
          layers:
          - layer: 'F.Cu'
        - sheet: 'B.Cu'
          layers:
          - layer: 'B.Cu'
        - sheet: 'Silkscreen bottom'
          layers:
          - layer: 'B.SilkS'
            color: '#00000000'
          mirror: true
        - sheet: 'Fabrication bottom'
          layers:
          - layer: 'B.Fab'
          - layer: 'B.Paste'
          - layer: 'B.Adhes'
          - layer: 'User.Comments'
          mirror: true
        - sheet: 'PCB bottom'
          layers:
          - layer: 'B.Cu'
          - layer: 'B.Mask'
            color: '#14332440'
          - layer: 'B.SilkS'
            color: '#e8b2a7ff'
          - layer: 'User.Comments'
          mirror: true
      plot_sheet_reference: true

...
definitions:
  KICAD_PDF_SCALING: 1.5
```
