### ISSUE TITLE
Highlights variables in Sass files

### ISSUE THREAD

**Issue by moll** [chrisbra/Colorizer#31]
Hey again,

Took another look at this plugin, so expect a few new issues. :)

Using it in a Sass file highlights variables with color names in them. So, for example, the following `black` gets a black background:

``` scss
.minor { color: $light-black }
```
